// Generated file - DO NOT EDIT MANUALLY
// This file is automatically generated by Spider's generateEmbeddedTemplates
// Source directory: src/

pub const EmbeddedTemplates = struct {

    home_index: []const u8 = @embedFile("features/home/views/index.html"),
    docs_pooling: []const u8 = @embedFile("features/docs/views/pooling.md"),
    docs_postgres: []const u8 = @embedFile("features/docs/views/postgres.md"),
    docs_request: []const u8 = @embedFile("features/docs/views/request.md"),
    docs_templates: []const u8 = @embedFile("features/docs/views/templates.md"),
    docs_router: []const u8 = @embedFile("features/docs/views/router.md"),
    docs_response: []const u8 = @embedFile("features/docs/views/response.md"),
    docs_websocket: []const u8 = @embedFile("features/docs/views/websocket.md"),
    docs_auth: []const u8 = @embedFile("features/docs/views/auth.md"),
    docs_forms: []const u8 = @embedFile("features/docs/views/forms.md"),
    docs_middleware: []const u8 = @embedFile("features/docs/views/middleware.md"),
    docs_metrics: []const u8 = @embedFile("features/docs/views/metrics.md"),
    docs_docker: []const u8 = @embedFile("features/docs/views/docker.md"),
    docs_static: []const u8 = @embedFile("features/docs/views/static.md"),
    docs_groups: []const u8 = @embedFile("features/docs/views/groups.md"),
    docs_http_client: []const u8 = @embedFile("features/docs/views/http_client.md"),
    docs_logger: []const u8 = @embedFile("features/docs/views/logger.md"),
    docs_shutdown: []const u8 = @embedFile("features/docs/views/shutdown.md"),
    docs_testing: []const u8 = @embedFile("features/docs/views/testing.md"),
    docs_quickstart: []const u8 = @embedFile("features/docs/views/quickstart.md"),
    docs_index: []const u8 = @embedFile("features/docs/views/index.html"),
    layout: []const u8 = @embedFile("shared/templates/layout.html"),
    site_nav: []const u8 = @embedFile("shared/templates/site-nav.html"),
    layout_docs: []const u8 = @embedFile("shared/templates/layout_docs.html"),

};
